# Generated by Django 5.0.4 on 2024-09-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ETUDIANT', 'etudiant'), ('MARCHAND', 'marchand'), ('ADMIN', 'admin')], default='', max_length=32),
        ),
    ]
