# Generated by Django 5.0.4 on 2024-10-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_admin_restaurant_admin_restaurant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ETUDIANT', 'étudiant'), ('MARCHAND', 'marchand'), ('ADMIN', 'admin')], default='', max_length=32),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.customuser',),
        ),
    ]
