# Generated by Django 5.0.4 on 2024-10-06 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_role_delete_admin_admin'),
        ('store', '0006_remove_restaurant_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('restaurant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.restaurant')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.customuser',),
        ),
    ]
