# Generated by Django 5.0.4 on 2024-09-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
    ]
