# Generated by Django 5.0.4 on 2024-09-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_restaurant_dish_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_choise',
            field=models.BooleanField(default=False),
        ),
    ]
