# Generated by Django 5.0.4 on 2024-10-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_dish_is_choise'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_max_number',
            field=models.IntegerField(default=1, verbose_name='max dish that student command '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='food_number',
            field=models.IntegerField(default=1, verbose_name='max food number of one day '),
            preserve_default=False,
        ),
    ]
