# Generated by Django 5.0.4 on 2024-10-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_dish_dish_max_number_dish_food_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='fruit',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='proteine',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
