# Generated by Django 5.0.4 on 2024-10-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_dish_fruit_dish_proteine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='admin',
        ),
    ]
