# Generated by Django 5.0.4 on 2024-09-24 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Card', 'Card'), ('Internal Balance', 'Internal Balance')], max_length=50)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('operator', models.CharField(max_length=256)),
                ('dish_number', models.IntegerField()),
                ('etudiant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='account.etudiant')),
            ],
        ),
    ]
