# Generated by Django 5.0.4 on 2024-09-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_order_etudiant_alter_order_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='etudiant',
            new_name='etudiant_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order',
            new_name='order_id',
        ),
    ]
